### ISSUE TITLE
support Grape style annotations to download jars & create classpaths on the fly?

### ISSUE THREAD

**Issue by jstrachan** [andrewoma/kotlin-script#1]
Great work - kotlin-script rocks :) 

Groovy's Grape has a nice use of annotations to let you specify dependencies via annotations
http://groovy.codehaus.org/Grape

Eclipse Aether's a handy little library for downloading jars from mvn repos & figuring out transitive dependencies:
http://eclipse.org/aether/

It'd be nice if you could use some annotations (or maybe a Kotlin module or something?) to be able to define classpaths/dependencies for scripts, so you could use other libraries in your shell scripts

**Comment by checketts** [comment]
I was just looking for this feature and I see it was just closed. I assume there is no `@Grab` style option for Kotilin scripts then?

**Comment by andrewoma** [comment]
@checketts It's coming eventually as part of this work: https://github.com/Kotlin/KEEP/blob/master/proposals/script-definition-template.md

However, progress is slow.
