### ISSUE TITLE
readme should detail out what's wrong with kotlinc

### ISSUE THREAD

**Issue by holgerbrandl** [andrewoma/kotlin-script#6]
This seems to work out of the box without using kotlins:

```bash
#!/usr/bin/env kotlinc -script

println("Hello from Kotlin!")
for (arg in args) {
    println("arg: $arg")
}
```
Startup performance seems reasonable, and the classpath can be defined as well if needed.

Maybe the docs could detail out how kotlins compares to kotlinc?

**Comment by andrewoma** [comment]
Hi, this predates any official scripting supports (it's 4 years old in fact). 

Kotlin's native scripting support has slowly been improving, but it still doesn't support caching of compiled scripts (this documented at https://github.com/andrewoma/kotlin-script#features)

The compiler performance has certainly improved, but "Startup performance seems reasonable" is clearly subjective. 

For hello world on my system `kotlins` is `0m0.128s` versus `kotlinc` of `0m1.520s` after caching.

```
$ time ./kotlinc-hello.kts 
Hello from Kotlin!

real	0m1.520s
user	0m3.521s
sys	0m0.286s
andrew@Andrews-MacBook-Pro.local ~/dev/projects/angular2-webpack-starter
$ time ./kotlins-hello.kts 
Hello from Kotlin!

real	0m1.659s
user	0m3.531s
sys	0m0.354s
andrew@Andrews-MacBook-Pro.local ~/dev/projects/angular2-webpack-starter
$ time ./kotlins-hello.kts 
Hello from Kotlin!

real	0m0.128s
user	0m0.094s
sys	0m0.039s
```

In general though, this is a hack until Kotlin provides better support - it's been 4 years and it still seems to add value

**Comment by holgerbrandl** [comment]
Thanks for the info. Indeed the startup performance gain because of the caching seems really significant. Do you know if there is a kotlin ticket for such a caching feature?
