### ISSUE TITLE
IDE

### ISSUE THREAD

**Issue by MarcinMoskala** [andrewoma/kotlin-script#9]
Is there a way to connect it with IntelliJ IDE? Because it is really important in Kotlin that it is statically typed and it includes hints from IDE.

**Comment by andrewoma** [comment]
Kotlin now has official scripting support that works in the IDE to some extent. See: https://kotlinlang.org/docs/tutorials/command-line.html#using-the-command-line-to-run-scripts

Basically you use an extension of `.kts`. 1.1 is supposed to include some enhancements that allow dependency resolution but I haven't investigated it yet.

There's also https://github.com/andrewoma/kotlin-scripting-kickstarter as another approach for full IDE support (note: I haven't updated it to 1.1 yet).
